### ISSUE TITLE
[Enchancement] Option to add custom enchants

### ISSUE THREAD

**Issue by iwantamommy** [Geolykt/EnchantmentsPlus#109]
When trying to hide flags with regular enchants, then add the custom ones,  it shows the custom ones and hides vanilla ones.

**Comment by Geolykt** [comment]
This is, if I understood you right, not possible due to how the plugin is built.
I'll still leave this open in case anyone finds a way of doing just that.

**Comment by Geolykt** [comment]
I've been able to implement this feature only for NBT gatherers (which is used by almost noone) but it is a bit finicky to use (i. e. already existing enchantments will not be hidden until you update them). I do not know how to make it better without sacrificing performance though.
And additionally it needs testing, the plugin used to apply the HIDE_ENCHANTS flag in order to do some hackery, which we do not do anymore. This is why this feature is disabled by default as otherwise you'd not see new enchantments in certain cases.
