### ISSUE TITLE
Support for Crossbow and trident

### ISSUE THREAD

**Issue by StevenDesroches** [Geolykt/EnchantmentsPlus#11]
Hey,
I was wondering if you were planning of adding support for the crossbow and the trident?
Because, I can make a PR for the crossbow and for the piercing mechanics.
I should have one for the trident in the near future

**Comment by Geolykt** [comment]
Nyes, that wasn't planned, however would be possible whenever I actually implement it so that admins can choose what belongs in which category (which would allow to say that dirt blocks are swords, for example). I did test around using Enchantment targets, but it ended up not being viable in any capacity
