### ISSUE TITLE
Disable players from getting Custom Enchants from enchantment table

### ISSUE THREAD

**Issue by Dryixz** [Geolykt/EnchantmentsPlus#134]
I recently run a server and i wanted them to buy the enchantments not to get them through enchantment table is there a way to disable this feature?

**Comment by Geolykt** [comment]
You can configure that through world.yml (and for the other worlds! Otherwise players may still obtain the enchantments in the nether for example) by setting the Probability of each enchantment to `0.0` (`-1.0` probably disables the enchantment outright - so beware there). Now that may be a little bit tedius, so you can just set the `enchant_rarity` of each world to `0.0` instead of `25.0`

**Comment by Dryixz** [comment]
Ah thank you i typed -1 to enchant_rarity and restarted the server but it still works but all i have to do is put 0.0 thank you very much
