### ISSUE TITLE
Is WorldGuard compatible with this plugin?

### ISSUE THREAD

**Issue by ToggleMountain** [Geolykt/EnchantmentsPlus#4]

**Comment by Geolykt** [comment]
It would be quite a desaster if the plugin would provide any compatibillity with WorldGuard since that is one of the most used plugin ever, so if there is an issue, report it asap with a description

Please provide a clearer explaination behind the question, but in essence, yes, most World protection plugins are supported and those who don't need to fix their shit. Although, I think there might be an issue with entities, but that would mean that something doesn't work and it purely speculation.

I'm closeing the issue since I belive it's answered, but feel free to ask more

**Comment by ToggleMountain** [comment]
Example: Using firestorm in pvp protected area, anyone could just spawn camp.

**Comment by ToggleMountain** [comment]
Thanks for reply btw

**Comment by Geolykt** [comment]
Firestorm? We had some problem with that one, but since I already tested that one enchantment in particular I can say that it's safe using towny, WorldGuard? Maybe
