### ISSUE TITLE
Add enchants to books with /ench

### ISSUE THREAD

**Issue by chrismwiggs** [Geolykt/EnchantmentsPlus#43]
Not a bug, but a feature request!

It would be handy to be able to add custom enchants to books with /ench <enchantment> or /ench give book <enchantment>. Helpful for testing and finding weird bugs but also to be able to give a custom enchant as a one-off if lost (easy when its a tool, but if someone loses a book I have to sort of tell them they're SOL).

**Comment by Geolykt** [comment]
That's actually a "bug" that I have not yet bothered to fix since there is a workaround for it:
`/ench <enchantment> <level> <modifier> <doNotification> true`. About the /ench give command, I should look into it given that the command hasn't had any changes in months while half the code got multiple overhauls.
