### ISSUE TITLE
It completley screws up groupmanager

### ISSUE THREAD

**Issue by Cozrona** [Geolykt/EnchantmentsPlus#57]

**Comment by Geolykt** [comment]
Groupmanager is a really bad plugin, consider not using it

I am speed

**Comment by Cozrona** [comment]
> Groupmanager is a really bad plugin, consider not using it
> 
> I am speed

then what rank plugin should i use

**Comment by Geolykt** [comment]
Enchantments+ does not modify any permissions, if it fucks up with GM consider staying with Superperms (bukkit default) or using Luckperms. Rights now your issues are super unspecific which is why they were closed on accounts of spam (and also are also hyper improbable as Enchantments+ does not modify permissions and is known to work with superperms)

**Comment by 99-i** [comment]
> > Groupmanager is a really bad plugin, consider not using it
> > I am speed
> 
> then what rank plugin should i use

make ur own XD

**Comment by Cozrona** [comment]
how im garb at coding lmao

**Comment by gecko10000** [comment]
Luckperms is practically an industry standard at this point. However, if you insist on solving this "issue" created by Group Manager, you'll have to go into more detail than "it messes up the plugin".
