### ISSUE TITLE
Switch and Terraforming do not get logged by coreprotect

### ISSUE THREAD

**Issue by Uboaaaaa** [Geolykt/EnchantmentsPlus#62]
When making changes to the world using the two enchantments, the interaction is not picked up by coreprotect, leaving no trace of who has done that.

I found that Pierce enchantment actually do get logged by coreprotect, so I'm wondering whether there's any way to make the two being logged as well.

**Comment by Geolykt** [comment]
Terraforming is an issue, Switch maybe?
The issue with switch is that there is simply no way of telling other plugins that a block has changed; the concept does not exist in Bukkit, which is why the Native Permission Query exists. Disableing it results in switch using questionable events that lead to exploits.

Either way, I'll look into a coreprotect/prism integration similar to that of the Native Permission Query.

**Comment by Geolykt** [comment]
Looked into the issue a bit more in-depth and I can tell that I will not support Coreprotect at all in the (near-) future. Coreprotect does not have an official-looking maven release and it does not have an explictit license. Because the plugin has so many downloads and does not have any github repo I won't do my traditional "Mind adding an explicit license" move.

I hope you understand the situation. Nonetheless I will add support for ~Prism~ (actually, LogBlock was the only one that was supported) which would lead that a third party could add support for Coreprotect if they have more concrete information on this.

**Comment by Geolykt** [comment]
Closing this since that is all I can do for now
