### ISSUE TITLE
Spartan throws NullPointerExceptions in connection to the Blizzard Enchantment

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#68]
I am getting ton of warns on the console...
![Screenshot_1](https://user-images.githubusercontent.com/84740054/119395007-98a8ef80-bcdb-11eb-925d-52ffb83d64f0.png)

**Comment by gecko10000** [comment]
Update to the latest version, but if the issue persists, the first time it happened will have the full, useful, stacktrace.

**Comment by Geolykt** [comment]
I do not recall that I fixed any NPEs anytime lately, so this is likely a bug that still persists.
Could you please give me the full stacktrace though (the first mention of the exception should have it)

**Comment by Restland** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/84740054/119398165-d871d600-bcdf-11eb-8653-b10b09a657b8.png)
Hope that helps, I can't update the plugin cause its on minehut.

**Comment by Geolykt** [comment]
It is unlikely that this has been fixed anytime lately, so I will have to ask the Spartan authors about whether they have an idea what I am doing wrong there. Fun :upside_down_face:

**Comment by Geolykt** [comment]
I do not know if you have any power on that given that it is Minehut, but can you run that on Java 15+? More helpfull NPEs are often a lifesaver of such issues

**Comment by Restland** [comment]
Run java15+ where?
Also I would like to add that it has a lot of bugs with world guard, people with smelt can mine sand on claimed areas , they don't destroy the sand but they get unlimited glass which is weird.

**Comment by Geolykt** [comment]
> Run java15+ where?

If you do not know how to run it with a latter version of Java, then you are likely not running with it.

> Also I would like to add that it has a lot of bugs with world guard, people with smelt can mine sand on claimed areas , they don't destroy the sand but they get unlimited glass which is weird.

I have experienced that bug myself but I have fixed it a year or so ago (which is why this fork exists) but it appears that that fix has since been broken. A workaround has been created for #47 but that is for a latter version of EnchantmentsPlus, however when updated you can simply switch https://github.com/Geolykt/EnchantmentsPlus/blob/4xx/resources/patches.yml#L12 to true and that bug should be solved.
Alternatively you can make use of #61 , whose use is described in https://github.com/Geolykt/EnchantmentsPlus/blob/4xx/resources/patches.yml#L13 though that requires v3.1.6 or later

**Comment by Geolykt** [comment]
I have talked with the plugin author and he said that it was indeed a null damager as I supected. This should be an easy fix though a bit strange given that it does not make sense that the arrow shooter somehow returns null at that frequency.

I currently have work to do, so that fix will be rolled over in a few (7 or so) more hours.
