### ISSUE TITLE
Germination enchantment does not consume bonemeal properly

### ISSUE THREAD

**Issue by Uboaaaaa** [Geolykt/EnchantmentsPlus#70]
**Steps to reproduce:**
Plant a field with seed.
Enchant your hoe with Germination.
Make sure that you have only **one** bone meal in your inventory.
Right click the crops.

The crops will grow but the bone meal will not be consumed.

**Configuration:**

```
- Germination:
    Probability: 0.5
    Tools: Hoe
    Name: Germination
    Max Level: 3
    Cooldown: 250
    Power: 1.0
    Effect area modifier: -1.0
```

**Comment by Geolykt** [comment]
Looking at the code I can see where the issue is, I will fix it whenever I am free to do so.

**Comment by Uboaaaaa** [comment]
I'm sorry to ask this... Will there be a build release for this patch? I might be too idiotic at java to compile the project myself...

**Comment by Geolykt** [comment]
The 4xx branch is kindof experimental right now (though it will get worse soon:tm: when I will try to do larger changes) so I will unlikely publish a build of that branch anytime soon. Though I will have to once 1.17 releases. The Java 16 hard requirement also means that that branch is less attractive to most people as Java 16 currently has a pretty low adoption (5%), but since it is mandatory for 1.17 it will not be too big of an issue.

To compile it yourself you only really require a Java 16+ and a working maven install and build it with `mvn clean package`, so pretty easy to do
