### ISSUE TITLE
Pretty laggy?

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#81]
After the latest update I have some issues with the TPS 
![image](https://user-images.githubusercontent.com/84740054/124509782-2ac40d80-dddb-11eb-880f-2989fd63d63a.png)

**Comment by Geolykt** [comment]
Hello.
Thank you for giving me a snippet of a timings report. However due to the architecture of the plugin, it is virtually useless and leads to more harm than good if I were to try to find the cause. Instead, it would be good to give me a [spark](https://github.com/lucko/spark) (or any other semi-decent profiler/sampler) report as it allows me to see the exact origin of the lag.

I hope you understand

**Comment by Restland** [comment]
What exactly do you want me to send? 
Thanks in advance.

**Comment by Geolykt** [comment]
Basically, install the spark plugin (if you haven't already), then do `/spark profiler` and after a while (just a few minutes) `/spark profiler --stop` (bonus points if you are in a currently low-TPS situation as that will increase the chance of finding something).
Then you will get a link like https://spark.lucko.me/InZzonmHwh (very similar to the usual timings). Since spark exposes some data  that you don't want to get exposed, it is also valid on clicking on `view: all` to get to the sources view and uncollapsing the entries where enchantmentsPlus is responsible and screenshotting that to send it here

**Comment by Restland** [comment]
Alright will do that tomorrow with the daily restart there are tons of people online right now so I don't want to do an emergancy maintance. Thank you. Will provide all the spark timings tommorow.

**Comment by Geolykt** [comment]
understandable.

**Comment by Restland** [comment]
![image](https://user-images.githubusercontent.com/84740054/124632696-3ff97480-de8d-11eb-9483-cfe7273edf32.png)
Hope that helps, if you need more let me know!

**Comment by Geolykt** [comment]
It would be best if you were to uncollapse the largest source recursively until the call tree becomes too large.
Right now I have little knowledge of what the original cause is

**Comment by Restland** [comment]
![image](https://user-images.githubusercontent.com/84740054/124639124-75559080-de94-11eb-9141-269cf190220a.png)

**Comment by Geolykt** [comment]
Ah I can work with that. Would be nice if you were to uncollapse the tracer entries a few more times, as otherwise I might fix the "wrong" mistake

**Comment by Restland** [comment]
I edited it.

**Comment by Geolykt** [comment]
Okay, that will be a bit harder to resolve. I'll see what I can do however

**Comment by Restland** [comment]
let me know what else can I do to fix the issue aswell. My server is hosted with Minehut and I can't update the plugin whenever I can they have to do it so. Thanks!

**Comment by Geolykt** [comment]
Sadly there isn't much you can do. And looking at the problematic code I don't think that it will be easy to fix for me (and will require testing as the fix will likely involve reducing the frequency at which the tracer method is called).
One thing you can do however is to reduce the power of the tracer enchantment or to remove it entirely.

**Comment by Restland** [comment]
How much power would you suggest?

**Comment by Geolykt** [comment]
No idea to be honest. I can give the tip that halving it should make the lag a quarter less potent (to some degree, the range is increased by 2 later on).

Currently the formula for the range (radius) is `Math.round(level * power) + 2` - the higher it is the more lag there should be

**Comment by Restland** [comment]
Thank you so much. The power was 4 I lowered it to 2 hopefully that will fix the issue.

**Comment by Geolykt** [comment]
oh yeah, that explains to why you have such issues with it.
Still going to optimize the method though

**Comment by Restland** [comment]
I never changed it tho, pretty bazaar. Thanks again.

**Comment by Geolykt** [comment]
then your probably changed the max level

**Comment by Restland** [comment]
You are right. I change the power to 0.3 now , it was 1.
