### ISSUE TITLE
Extraction ignore claims

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#85]
Extraction ignores the grief prevention plugin when used on blocks like iron ore and gold ore.

**Comment by Geolykt** [comment]
I haven't heard of any similar issues and have yet to reproduce it over the last 18 months. I'll close it as I believe that I have fixed the issue years ago. If anyone thinks otherwise, feel free to say that aloud so I'll take a deeper look (Remember: I won't investigate something that doesn't make any noise).
