### ISSUE TITLE
Enchantments are not always functional

### ISSUE THREAD

**Issue by Waterghosteus97** [Geolykt/EnchantmentsPlus#94]
I am playing on a Paper server 1.17.1 And noticed that if we enchant an item using an enchanted book that has one of the enchantments from this plugin, that the enchantment glint appears on the item, as though it is enchanted, but no lore or any enchantment name is applied to the item. Furthermore, the effect of the enchantment seems to be null as well. 

I have tried the same enchantments on the same items, with the only difference being whether the enchantments were applied through commands or through the anvil, and the ones through the anvil never work, while the command enchanted items work.

I haven't yet had the opportunity to test this with an item enchanted from an enchanting table, but I presume it should be functional, as that is most likely the primary intended path to acquiring the enchantments from this plugin.

**Comment by Geolykt** [comment]
I've been getting these kinda of issues quite often, so it's just not you - frankly I do not see why it should not be working but I guess not testing it myself doesn't help.
It also doesn't help that I don't enjoy playing minecraft anymore nor enjoy coding with bukkit.

However your command vs anvil story is quite interesting because both are mostly the same in theory. What happens if you switch the `1xx-anvil-merger` to true (if false was the original value) or false (if true was the original value) within the patches.yml file?
Enchanting table is actually the least tested way of obtaining the enchantments and I have also heard reports of it being bork (did some spigot update break everything?)

**Comment by Geolykt** [comment]
I was unable to reproduce it on a fresh paper server with default settings. Perhaps there is something different yet significant with our setups?
