### ISSUE TITLE
Warns in the console

### ISSUE THREAD

**Issue by Restland** [Geolykt/EnchantmentsPlus#99]
![unknown (2)](https://user-images.githubusercontent.com/84740054/138332574-19ae8378-2bfb-43d1-a9fc-7f080c5498cf.png)
Its spamming the console like crazy is there a speicific way to find the problem?

**Comment by Geolykt** [comment]
Oh no, this doesn't look good. Could you give me the first occurence of "Enchantments_plus v3.1.6 generated an exception"? The server eventually supresses the stacktraces due to performance reasons, however I need one to be able to debug the issue. Judging from the frequency of the exception and prior knowledge it does appear to be something similar to #68 (even the same task ID!). So yeah, another instance of the shooter suddenly going null I suppose

**Comment by Restland** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/84740054/138338480-e4b94ed2-50c1-4724-a30e-1ffda550377d.png)

**Comment by Restland** [comment]
Hopefully that helps, it creates tons of spam in the console which makes the server hard to work on

**Comment by Geolykt** [comment]
looks like that is going to be an easy fix. Thanks for reporting it, I'll resolve that in a sec

**Comment by Restland** [comment]
WIll I have to do any actions?

**Comment by Geolykt** [comment]
Try restarting the server, if that does not work then I am a bit confused. I have yet to find the root cause of the issue (only the symptoms have been dealt with right now). Given the version of the plugin I might have accidentally fixed this, so perhaps that is why I did not find any clues to the root cause.

The other possibillity is that spigot has some strange implementation of AbstractArrow#hashcode() and AbstractArrow#equals() which may cause issues with the hashmap

The third possibillity is that there is a thread safety issue, but that is pretty much impossible given that I never call anything there off-thread.

Fourth possibillity is that there is a bitflip. Okay, perhaps not

**Comment by Restland** [comment]
Well the daily restart of the server is planned to happen tomorrow morning so I can't force a restart now since a lot of players are online. Since I am using Minehut will the plugin update by itself since they changed the file manager?

**Comment by Restland** [comment]
Also one more thing that is happening, people CAN'T compine custom enchants books on their weapons when I can. This started happening today out of nowhere. 
![image](https://user-images.githubusercontent.com/84740054/138345664-10ba778a-c185-4132-bd72-68a14dd3ffc1.png)

**Comment by Restland** [comment]
Also this happened today people can't seem to compine custom enchants in anvil with their weapons. This started happening today out of nowhere.
![image](https://user-images.githubusercontent.com/84740054/138345790-8fd2b7c6-5af0-4c7b-967b-7b8c2c61e642.png)

**Comment by Geolykt** [comment]
> Also this happened today people can't seem to compine custom enchants in anvil with their weapons. This started happening today out of nowhere. ![image](https://user-images.githubusercontent.com/84740054/138345790-8fd2b7c6-5af0-4c7b-967b-7b8c2c61e642.png)

At some point I have to do Anvil Refractor the 4th, or just delete anvil merging alltogether and offload it to a custom GUI. It has caused enough pain already.

It is unlikely that Minehut will update you given that you are still on 3.1.6 when 4.0.0 and 4.0.1 (latest) was released 4 months ago, this may have something to do with you still using 1.16 and 4.0.x supporting 1.17, which is why Minehut chooses to not roll it out? Idk

**Comment by Restland** [comment]
I am using 1.16.5, minehut released 1.17.1 2 days ago with tons of issues thats why I hesitate to update. 
The thing is if I choose to remove the plugin and update it by myself all of the settings will be removed. If I reinstall the plugin with the settings wiped will all the items that the players have work? Or the custom enchants will no longer work for them?

**Comment by Geolykt** [comment]
Using 4.x+ default settings on 1.16 servers will lead to very unexpected behaviour with certain enchantments, otherwise if you use your old settings it should be perfectly fine.

Also, what is your `1xx-anvil-merger` setting in the patches.yml config file?

**Comment by Restland** [comment]
> Using 4.x+ default settings on 1.16 servers will lead to very unexpected behaviour with certain enchantments, otherwise if you use your old settings it should be perfectly fine.
> 
> Also, what is your `1xx-anvil-merger` setting in the patches.yml config file?

Its set to false.

**Comment by Geolykt** [comment]
Put it to true and see what happens (after the server eventually restarts), that being said I know that it also has it's bugs (could also be exploits, it's been a year since i removed it by default), but under spigot (which is what you seem to be using) it is usually better than keeping it disabled as otherwise anvil merging works to almost no degree

**Comment by Restland** [comment]
I will try to thank you so much, also  can you reply to my previous questions please?
If I remove the plugin and wipe all the data after I reinstall it all the items with custom enchants will work normally or they will be broken?

**Comment by Geolykt** [comment]
they will work (unless you remove the world files heh)

**Comment by Restland** [comment]
> they will work (unless you remove the world files heh)

The thing is to install a new jar file on minehut you have to completly remove the custom enchants jar+folder file to install a new one and I don't want plaeyrs to lose their progress that why i am asking here to make sure updating it will not cause any issues.

**Comment by Geolykt** [comment]
The actual enchantments are stored as lore (by default, under some settings they may be stored as NBT, but that has more or less the same result), removing the plugin only disables the enchantments but if the plugin is reinstalled they will be reenabled

**Comment by Restland** [comment]
> The actual enchantments are stored as lore (by default, under some settings they may be stored as NBT, but that has more or less the same result), removing the plugin only disables the enchantments but if the plugin is reinstalled they will be reenabled

Thank you so much.

**Comment by Restland** [comment]
It keeps happening most of the time, updating might fix it?

**Comment by Geolykt** [comment]
I'll release what has been done then. It does not fix the issue outright but that would be the least I can do

**Comment by Geolykt** [comment]
Has this bug been occuring lately?

**Comment by Restland** [comment]
> Has this bug been occuring lately?

It stopped since I swithed to paper.

**Comment by Geolykt** [comment]
Huh that is interesting. But glad to know that it does not occur again

**Comment by Restland** [comment]
Yeah pretty weird, it happened to my test server aswell after I switched from paper to spigot. Atleast in the main server is fixes the issue.
